### ISSUE TITLE
HTTPS-Übertragung

### ISSUE THREAD

**Issue by webyourlife** [abkekvw/evangtermine#1]
Hallo, ich darf die Evangelischen Jugenden von Neustadt, Schwabach, Bamberg undHersbruck bei der Implementierung unterstützen und versuche mit der Version 2.0.7 eine sichere Verbindung herzustellen. Leider ist dies auch nicht bei Nutzung eines https-Hosts (plugin.tx_evangtermine_pi1.host = https://www.evangelische-termine.de) gelungen und die Seite wird immer als potentiell unsicher ausgegeben: [Mixed-Content] Der Ursprung "https://www.ej-bamberg.de" wurde in einem sicheren Kontext geladen und hat eine unsichere image-Ressource bei "http://www.evangelische-termine.de/bundles/vket/images/ical.gif" geladen, die optional blockiert werden kann. Ist es möglich die Abfrage über https zu generieren?
Vielen Dank Joachim

**Comment by abkekvw** [comment]
Hallo,
gibt es dazu eine URL, wo der Effekt zu sehen ist?

Viele Grüße,

Christoph Roth

**Comment by webyourlife** [comment]
Hi, ja natürlich: https://www.ej-bamberg.de/unsere-angebote/freizeiten-und-veranstaltungen/?no_cache=1&tx_evangtermine_list%5BID%5D=4765040&tx_evangtermine_list%5Baction%5D=show&tx_evangtermine_list%5Bcontroller%5D=Eventcontainer
Viele Grüße & besten Dank
Joachim

**Comment by rumpfwerk** [comment]
Im entsprechenden Template werden die Pfade der Icons (die hier über HTTP geladen werden) über den in den Konstanten (oder war es die die Extensionkonfiguration?) angegeben. 
Hier ist vermutlich auch der Host "http://www.evangelische-termine.de" angegeben und nicht "https://www.evangelische-termine.de"

VG Veit Rumpf

**Comment by webyourlife** [comment]
Hi, ich habe es gefunden … in der Template-Datei von evangtermine  Private/Templates/Eventcontainer/Show.html wird ein HTML-Block geladen, der die Links zu den Icons der Social Media-Seiten einbindet. Die img scr werden z. B. so aufgerufen:  src="http://{eventhost}/bundles/vket/images/ical.gif" … das ist irgendwie suboptimal. Aber immerhin leicht zu korrigieren. Danke für den Schubs! Leider kann man den Host (noch, V2.0.7) nicht über die Konstanten einstellen und an dieser Stelle würde da auch nichts greifen.
Joachim

**Comment by rumpfwerk** [comment]
ja genau. Irgendwo in der Extension hat man ja initial eingestellt, von welchem Server die Termine kommen sollen. (je nach Kirche gibt es ja verschiedene). Dort ggf. die https-Variante einstellen, vermute ich . 
VG Veit

**Comment by abkekvw** [comment]
> Hi, ich habe es gefunden … in der Template-Datei von evangtermine Private/Templates/Eventcontainer/Show.html wird ein HTML-Block geladen, der die Links zu den Icons der Social Media-Seiten einbindet. Die img scr werden z. B. so aufgerufen: src="http://{eventhost}/bundles/vket/images/ical.gif" … das ist irgendwie suboptimal. Aber immerhin leicht zu korrigieren. Danke für den Schubs! Leider kann man den Host (noch, V2.0.7) nicht über die Konstanten einstellen und an dieser Stelle würde da auch nichts greifen.
> Joachim

In dem genannten Template (Show.html) stehen in der Version 2.0.7 keine fest kodierten Protokolle mehr drin, das sieht dort so aus: 

src="//{eventhost}/bundles/vket/images/ical.gif"

Wenn Du dort ein "http://" stehen hattest, war das nicht das Template aus der 2.0.7. oder ggf. bei Dir auf eigene Templates überschrieben und da stand es noch drin.

**Comment by abkekvw** [comment]
> ja genau. Irgendwo in der Extension hat man ja initial eingestellt, von welchem Server die Termine kommen sollen. (je nach Kirche gibt es ja verschiedene). Dort ggf. die https-Variante einstellen, vermute ich .
> VG Veit

Das stimmt, von den Kirchenservern wird noch per http:// abgerufen, das werde ich ändern in https://

Aber über diese URL werden nur XML-Daten abgerufen, das sollte sich eigentlich nicht auswirken.
