### ISSUE TITLE
PHP 8.2 and file_get_contents with bind 0:0 error

### ISSUE THREAD

**Issue by ShortSnow** [abkekvw/evangtermine#3]
Hi,

 PHP Warning: file_get_contents(): Invalid IP Address: 0 in /typo3conf/ext/evangtermine/Classes/Domain/Repository/EventcontainerRepository.php and
PHP Warning: file_get_contents(): Invalid IP Address: 0 in /typo3conf/ext/evangtermine/Classes/Util/CategoryUtil.php

~~~
		// URL abfragen, nur IPv4 Auflösung
		$streamContext = stream_context_create(array(
			'socket' => array('bindto' => '0:0') 
		));
		#$rawXml = file_get_contents($url, false, $streamContext);
		$rawXml = file_get_contents($url, false);
~~~

The parameter bindto works not as exceptet with php 8.2. I changed in both files `file_get_contents($url, false, $streamContext)` to `file_get_contents($url, false);`

For me it works now. Thx a lot for this extension and happy coding.

Arne

**Comment by abkekvw** [comment]
Hi,

thanks for the advice! There are also a few other issues with PHP 8.x and I plan to have an extension update next week.

Kind regards, 

Christoph
